In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

fact_sales = pd.read_parquet("../data/FACT_SALES.parquet")
dim_product = pd.read_parquet("../data/DIM_PRODUCT.parquet")

In [ ]:
csv_path = "/content/drive/MyDrive/retailcorps.csv"

In [ ]:
import duckdb

con = duckdb.connect()

csv_path = "/content/drive/MyDrive/retailcorps.csv"

con.execute(f"""
CREATE TABLE retail_raw AS
SELECT *
FROM read_csv_auto(
    '{csv_path}',
    all_varchar = true
)
""")

In [ ]:
con.sql("SELECT * FROM retail_raw LIMIT 20").df()

In [ ]:
con.sql("""SELECT COUNT (*) FROM retail_raw""").fetchdf()

In [ ]:
con.sql("""SELECT LoyaltyProgram FROM retail_raw""").fetchdf()

In [ ]:
con.execute("""DESCRIBE retail_raw""").fetchdf()
#Invoice date à changer en date, quantity en INT , UnitPriceGBP et UnitCostGBP en DOUBLE , DISCOUNT RATE en DOUBLE, DELIVERYTIME en INT,

In [ ]:
con.sql("""SELECT DeliveryTime FROM retail_raw""").fetchdf()

In [ ]:
import pandas as pd

colonnes = con.execute("DESCRIBE retail_raw").fetchdf()['column_name'].tolist()
total = con.execute("SELECT COUNT(*) FROM retail_raw").fetchone()[0]

audit = []
for col in colonnes:
    nb_manquants = con.execute(f"SELECT COUNT(*) - COUNT({col}) FROM retail_raw").fetchone()[0]
    audit.append({'colonne': col, 'nb_manquants': nb_manquants})

audit_df = pd.DataFrame(audit).sort_values('nb_manquants', ascending=False)
audit_df

In [ ]:
con.sql("""SELECT country FROM retail_raw""").fetchdf()

In [ ]:
con.sql("""SELECT CustomerID FROM retail_raw""").fetchdf()

In [ ]:
con.sql("SUMMARIZE (SELECT (*) FROM retail_raw)").fetchdf()

In [ ]:
con.sql("""SELECT customerID, LoyaltyProgram FROM  retail_raw WHERE customerID is null""").df()

In [ ]:
con.sql("""SELECT Description FROM retail_raw""").fetchdf()

                                 Description
0        15CM CHRISTMAS GLASS BALL 20 LIGHTS
1                         PINK CHERRY LIGHTS
2                        WHITE CHERRY LIGHTS
3               RECORD FRAME 7" SINGLE SIZE
4             STRAWBERRY CERAMIC TRINKET BOX
...                                      ...
1072702               VINTAGE BILLBOARD MUG
1072703            PARTY TIME PENCIL ERASERS
1072704     RETROSPOT TEA SET CERAMIC 11 PC
1072705      PAPER CHAIN KIT 50'S CHRISTMAS
1072706     HANGING WOOD AND FELT BUTTERFLY

[1072707 rows x 1 columns]

In [ ]:
con.execute("""
    SELECT *
    FROM retail_raw
    WHERE Invoice = '580366'
""").fetchdf()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,1046854,580366,20978,36 PENCILS TUBE SKULLS,1,2011-12-02 16:38:00,None,United Kingdom,STATIONERY,Stationery,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
1,1046855,580366,21901,"KEY FOB , BACK DOOR",1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
2,1046856,580366,22197,POPCORN HOLDER,2,2011-12-02 16:38:00,None,United Kingdom,HOME,Home decoration,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
3,1046857,580366,22428,ENAMEL FIRE BUCKET CREAM,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
4,1046858,580366,22431,WATERING CAN BLUE ELEPHANT,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
5,1046859,580366,22466,FAIRY TALE COTTAGE NIGHT LIGHT,1,2011-12-02 16:38:00,None,United Kingdom,HOME,Home decoration,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
6,1046860,580366,22562,MONSTERS STENCIL CRAFT,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
7,1046861,580366,22585,PACK OF 6 BIRDY GIFT TAGS,2,2011-12-02 16:38:00,None,United Kingdom,GIFT,Gifts,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
8,1046862,580366,22624,IVORY KITCHEN SCALES,1,2011-12-02 16:38:00,None,United Kingdom,KITCHEN,Kitchenware,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
9,1046863,580366,22688,DOORMAT PEACE ON EARTH BLUE,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
10,1046864,580366,22739,RIBBON REEL CHRISTMAS SOCK BAUBLE,2,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
11,1046865,580366,22835,HOT WATER BOTTLE I AM SO POORLY,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
12,1046866,580366,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,2,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
13,1046867,580366,22919,HERB MARKER MINT,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
14,1046868,580366,22920,HERB MARKER BASIL,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
15,1046869,580366,22921,HERB MARKER CHIVES,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
16,1046870,580366,22923,FRIDGE MAGNETS LES ENFANTS ASSORTED,6,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
17,1046871,580366,23012,GLASS APOTHECARY BOTTLE PERFUME,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
18,1046872,580366,23014,GLASS APOTHECARY BOTTLE ELIXIR,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
19,1046873,580366,23050,RECYCLED ACAPULCO MAT GREEN,2,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
20,1046874,580366,23080,RED METAL BOX TOP SECRET,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
21,1046875,580366,23082,SET 6 PAPER TABLE LANTERN HEARTS,2,02/12/2011 16:38,None,United Kingdom,STATIONERY,Stationery,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
22,1046876,580366,23083,SET 6 PAPER TABLE LANTERN STARS,2,2011-12-02 16:38:00,None,United Kingdom,STATIONERY,Stationery,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
23,1046877,580366,23084,RABBIT NIGHT LIGHT,1,2011-12-02 16:38:00,None,United Kingdom,HOME,Home decoration,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
24,1046878,580366,23096,PETIT TRAY CHIC,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
25,1046879,580366,23169,CLASSIC GLASS COOKIE JAR,6,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
26,1046880,580366,23193,BUFFALO BILL TREASURE BOOK BOX,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
27,1046881,580366,23206,LUNCH BAG APPLE DESIGN,1,2011-12-02 16:38:00,None,United Kingdom,HOME,Home decoration,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
28,1046882,580366,23247,BISCUIT TIN 50'S CHRISTMAS,1,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
29,1046883,580366,23311,VINTAGE CHRISTMAS STOCKING,1,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
30,1046884,580366,23312,VINTAGE CHRISTMAS GIFT SACK,1,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
31,1046885,580366,23343,JUMBO BAG VINTAGE CHRISTMAS,2,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
32,1046886,580366,23344,JUMBO BAG 50'S CHRISTMAS,1,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
33,1046887,580366,23350,ROLL WRAP VINTAGE SPOT,4,2011-12-02 16:38:00,None,United Kingdom,GIFT,None,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
34,1046888,580366,23353,6 GIFT TAGS VINTAGE CHRISTMAS,3,2011-12-02 16:38:00,None,United Kingdom,SEASONAL,Seasonal,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
35,1046889,580366,23393,HOME SWEET HOME CUSHION COVER,2,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
36,1046890,580366,23396,LE JARDIN BOTANIQUE CUSHION COVER,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
37,1046891,580366,23397,FOOT STOOL HOME SWEET HOME,2,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
38,1046892,580366,23489,VINTAGE BELLS GARLAND,4,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
39,1046893,580366,23559,WOODLAND BUNNIES LOLLY MAKERS,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
40,1046894,580366,23583,LUNCH BAG PAISLEY PARK,1,2011-12-02 16:38:00,None,United Kingdom,GIFT,Gifts,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
41,1046895,580366,35970,ZINC FOLKART SLEIGH BELLS,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
42,1046896,580366,84879,ASSORTED COLOUR BIRD ORNAMENT,8,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
43,1046897,580366,84946,ANTIQUE SILVER T-LIGHT GLASS,6,2011-12-02 16:38:00,None,United Kingdom,HOME,Home decoration,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
44,1046898,580366,DOT,DOTCOM POSTAGE,1,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
45,1046889,580366,23393,HOME SWEET HOME CUSHION COVER,2,2011-12-02 16:38:00,None,United Kingdom,OTHER,Other,...,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP

In [ ]:
con.execute("""
    SELECT *
    FROM retail_raw
    WHERE StockCode = '21490'
""").fetchdf()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,301,489488,21490,SET OF THREE 50'S GIFT WRAPS,3,2009-12-01 10:59:00,17238.0,United Kingdom,GIFT,Gifts,...,Marketplace,PayPal,WH-UK-02,SPRING,0.05,Completed,4,Europe,Western Europe,GBP
1,676,489529,21490,SET OF THREE 50'S GIFT WRAPS,2,2009-12-01 11:51:00,17984.0,United Kingdom,GIFT,Gifts,...,Online,Card,WH-UK-01,SPRING,0.05,Completed,10,Europe,Western Europe,GBP
2,1157,489552,21490,SET OF THREE 50'S GIFT WRAPS,3,2009-12-01 12:36:00,17063.0,United Kingdom,GIFT,Gifts,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,4,Europe,Western Europe,GBP
3,1218,489556,21490,SET OF THREE 50'S GIFT WRAPS,3,2009-12-01 12:47:00,15719.0,United Kingdom,GIFT,Gifts,...,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,10,Europe,Western Europe,GBP
4,1560,489572,21490,SET OF THREE 50'S GIFT WRAPS,2,2009-12-01 13:29:00,17611.0,United Kingdom,GIFT,Gifts,...,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,9,Europe,Western Europe,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,344207,522966,21490,SET OF THREE 50'S GIFT WRAPS,8,2010-09-19 13:01:00,16007.0,United Kingdom,GIFT,Gifts,...,Online,Card,WH-UK-01,XMAS,0.15,Cancelled,7,Europe,Western Europe,GBP
61,345626,523005,21490,SET OF THREE 50'S GIFT WRAPS,5,2010-09-19 16:20:00,12748.0,United Kingdom,GIFT,Gifts,...,Store,Bank transfer,WH-UK-01,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP
62,345630,523005,21490,SET OF THREE 50'S GIFT WRAPS,1,2010-09-19 16:20:00,12748.0,United Kingdom,GIFT,Gifts,...,Store,Bank transfer,WH-UK-01,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP
63,346091,523019,21490,SET OF THREE 50'S GIFT WRAPS,1,2010-09-20 11:24:00,17811.0,United Kingdom,GIFT,Gifts,...,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,15,Europe,Western Europe,GBP
64,347562,523193,21490,None,3,2010-09-20 17:42:00,None,United Kingdom,OTHER,Other,...,Phone,Invoice,WH-UK-02,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP

In [ ]:
con.execute("""
    SELECT Invoice,
           COUNT(*) AS nb_lignes,
           COUNT(DISTINCT CustomerID) AS nb_customerID_distincts,
           SUM(CASE WHEN CustomerID IS NULL OR TRIM(CustomerID) = '' THEN 1 ELSE 0 END) AS nb_vides
    FROM retail_raw
    GROUP BY Invoice
    HAVING nb_vides > 0 AND nb_customerID_distincts >= 1
    LIMIT 20
""").fetchdf()

    Invoice  nb_lignes  nb_customerID_distincts  nb_vides
0    489437         23                        1       1.0
1    489443          7                        1       1.0
2    489536        131                        1       2.0
3    489545         32                        1       1.0
4    489573         32                        1       1.0
5    489594         51                        1       4.0
6    489640         27                        1       1.0
7   C489643          5                        1       1.0
8    489672         32                        1       1.0
9    489683         46                        1       1.0
10   489782         22                        1       1.0
11   489791         65                        1       1.0
12   489797         26                        1       1.0
13   489802         45                        1       1.0
14   489812         25                        1       1.0
15   489814         89                        1       1.0
16   489837         47                        1       1.0
17   489863         18                        1       1.0
18   489866        120                        1       4.0
19   489875         95                        1       2.0

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT
        * EXCLUDE (CustomerID),
        COALESCE(
            NULLIF(TRIM(CustomerID), ''),
            MAX(NULLIF(TRIM(CustomerID), '')) OVER (PARTITION BY Invoice)
        ) AS CustomerID
    FROM retail_raw
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.execute("""
    SELECT COUNT(*) AS toujours_vides
    FROM retail_clean
    WHERE CustomerID IS NULL OR TRIM(CustomerID) = ''
""").fetchdf()

   toujours_vides
0          244253

In [ ]:
con.execute("""
    SELECT Invoice, CustomerID, *
    FROM retail_raw
    WHERE Invoice IN (
        SELECT Invoice
        FROM retail_raw
        WHERE CustomerID IS NULL OR TRIM(CustomerID) = ''
        LIMIT 1
    )
""").fetchdf()

,Invoice,CustomerID,OrderLineID,Invoice_1,StockCode,Description,Quantity,InvoiceDate,CustomerID_1,Country,...,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,489437,None,32,489437,22143,CHRISTMAS CRAFT HEART DECORATIONS,6,2009-12-01 09:08:00,None,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
1,489437,15362.0,33,489437,22145,CHRISTMAS CRAFT HEART STOCKING,6,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
2,489437,15362.0,34,489437,22130,PARTY CONE CHRISTMAS DECORATION,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
3,489437,15362.0,35,489437,21364,PEACE SMALL WOOD LETTERS,2,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
4,489437,15362.0,36,489437,21360,JOY LARGE WOOD LETTERS,1,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
5,489437,15362.0,37,489437,21351,CINAMMON & ORANGE WREATH,2,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
6,489437,15362.0,38,489437,21352,EUCALYPTUS & PINECONE WREATH,2,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
7,489437,15362.0,39,489437,35400,WOODEN BOX ADVENT CALENDAR,2,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
8,489437,15362.0,40,489437,20695,FLORAL BLUE MONSTER,3,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
9,489437,15362.0,41,489437,37370,RETRO COFFEE MUGS ASSORTED,12,01/12/2009 09:08,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
10,489437,15362.0,42,489437,10002,INFLATABLE POLITICAL GLOBE,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
11,489437,15362.0,43,489437,84507B,STRIPES DESIGN MONKEY DOLL,6,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
12,489437,15362.0,44,489437,20703,BLUE PADDED SOFT MOBILE,3,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
13,489437,15362.0,45,489437,21987,PACK OF 6 SKULL PAPER CUPS,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
14,489437,15362.0,46,489437,21989,PACK OF 20 SKULL PAPER NAPKINS,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
15,489437,15362.0,47,489437,84970S,HANGING HEART ZINC T-LIGHT HOLDER,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
16,489437,15362.0,48,489437,20971,PINK BLUE FELT CRAFT TRINKET BOX,12,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
17,489437,15362.0,49,489437,22271,FELTCRAFT DOLL ROSIE,6,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
18,489437,15362.0,50,489437,22272,FELTCRAFT DOLL MARIA,6,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
19,489437,15362.0,51,489437,22274,FELTCRAFT DOLL EMILY,6,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
20,489437,15362.0,52,489437,21912,VINTAGE SNAKES & LADDERS,4,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
21,489437,15362.0,53,489437,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
22,489437,15362.0,54,489437,22112,CHOCOLATE HOT WATER BOTTLE,3,2009-12-01 09:08:00,15362.0,United Kingdom,...,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT
        r.* EXCLUDE (CustomerID),
        COALESCE(
            NULLIF(TRIM(r.CustomerID), ''),
            (SELECT MAX(NULLIF(TRIM(r2.CustomerID), ''))
             FROM retail_raw r2
             WHERE r2.Invoice = r.Invoice)
        ) AS CustomerID
    FROM retail_raw r
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.execute("""
    SELECT COUNT(*) AS toujours_vides
    FROM retail_clean
    WHERE CustomerID IS NULL OR TRIM(CustomerID) = ''
""").fetchdf()

   toujours_vides
0          244253

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * EXCLUDE (CustomerID),
        COALESCE(NULLIF(TRIM(CustomerID), ''), 'GUEST') AS CustomerID
    FROM retail_clean
""")

In [ ]:
con.execute("""
    SELECT COUNT(*) AS toujours_vides
    FROM retail_clean
    WHERE CustomerID IS NULL OR TRIM(CustomerID) = ''
""").fetchdf()

   toujours_vides
0               0

In [ ]:
con.sql("UPDATE retail_clean SET Country = LOWER(TRIM(Country))")

con.sql("SELECT DISTINCT Country FROM retail_clean").fetchdf()

                 Country
0         united kingdom
1                   u.k.
2                 france
3          great britain
4            netherlands
5                 sweden
6                ireland
7                 canada
8                holland
9                    usa
10  united arab emirates
11                 spain
12             singapore
13               belgium
14                 italy
15                   aus
16                poland
17                brazil
18               denmark
19               germany
20                 japan
21                  eire
22                    fr
23                    uk
24           deutschland
25   republic of ireland
26                    de
27                norway
28           switzerland
29              portugal
30             australia
31                    nl
32                    ch
33          south africa

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT *
    REPLACE(LOWER(
          CASE Country
              WHEN 'uk' THEN 'united kingdom'
              WHEN 'u.k.' THEN 'united kingdom'
              WHEN 'great britain' THEN 'united kingdom'
              WHEN 'Great Britain' THEN 'united kingdom'
              WHEN 'deutschland' THEN 'germany'
              WHEN 'de' THEN 'germany'
              WHEN 'eire' THEN 'ireland'
              WHEN 'republic of ireland' THEN 'ireland'
              WHEN 'nl' THEN 'netherlands'
              WHEN 'holland' THEN 'netherlands'
              WHEN 'fr' THEN 'france'
              WHEN 'ch' THEN 'switzerland'
              WHEN 'aus' THEN 'australia'
              ELSE Country
          END ) AS Country)
  FROM retail_clean;
""").fetchdf()

     Count
0  1072707

In [ ]:
con.execute("""
    SELECT *
    FROM retail_clean
    WHERE WarehouseID IS NULL
    ORDER BY Country""").fetchdf()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID
0,753669,556917,22138,BAKING SET 9 PIECE RETROSPOT,48,2011-06-15 13:37:00,australia,OTHER,Other,Other,...,Card,None,CLEARANCE,0.2,Completed,4,Oceania,Australia and New Zealand,AUD,12415.0
1,795079,560491,23201,JUMBO BAG ALPHABET,1,2011-07-19 10:51:00,australia,GIFT,Gifts,Occasions,...,Card,None,WELCOME10,0.1,Completed,6,Oceania,Australia and New Zealand,AUD,12415.0
2,84104,497210,22386,JUMBO BAG PINK WITH WHITE SPOTS,10,2010-02-07 12:41:00,belgium,GIFT,Gifts,Occasions,...,Card,None,NONE,0.0,Completed,2,Europe,Western Europe,EUR,12402.0
3,816796,562445,POST,POSTAGE,3,2011-08-04 18:51:00,belgium,OTHER,Other,Other,...,Invoice,None,SPRING,0.05,Completed,4,Europe,Western Europe,EUR,12417.0
4,949424,573173,85230B,CINNAMON SCENTED VOTIVE CANDLE,24,2011-10-28 10:10:00,belgium,HOME,Home decoration,Interior,...,PayPal,None,SPRING,0.05,Completed,10,Europe,Western Europe,EUR,12362.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,1050369,580611,22495,SET OF 2 ROUND TINS CAMEMBERT,1,2011-12-05 11:49:00,united kingdom,OTHER,Other,Other,...,Card,None,CLEARANCE,0.2,Completed,13,Europe,Western Europe,GBP,12748.0
1771,1050509,580612,23041,PAPER LANTERN 9 POINT SNOW STAR,4,2011-12-05 11:58:00,united kingdom,STATIONERY,Stationery,Office,...,Card,None,SPRING,0.05,Completed,5,Europe,Western Europe,GBP,GUEST
1772,1050528,580612,23300,GARDENERS KNEELING PAD CUP OF TEA,12,2011-12-05 11:58:00,united kingdom,KITCHEN,Kitchenware,Interior,...,Card,None,SPRING,0.05,Completed,5,Europe,Western Europe,GBP,GUEST
1773,1050825,580615,22722,SET OF 6 SPICE TINS PANTRY DESIGN,8,2011-12-05 12:05:00,united kingdom,HOME,Home decoration,Interior,...,Card,None,CLEARANCE,0.2,Completed,8,Europe,Western Europe,GBP,16873.0
1774,61993,494891,22326,ROUND SNACK BOXES SET OF4 WOODLAND,1,2010-01-19 13:23:00,usa,OTHER,Other,Other,...,PayPal,None,CLEARANCE,0.2,Completed,13,North America,North America,USD,12733.0

In [ ]:
con.execute("""
    SELECT Invoice, WarehouseID, COUNT(*) AS nb
    FROM retail_clean
    WHERE WarehouseID IS NULL
    GROUP BY Invoice, WarehouseID
    ORDER BY Invoice, nb DESC
""").fetchdf()

      Invoice WarehouseID  nb
0      489488        None   1
1      489514        None   1
2      489544        None   1
3      489594        None   1
4      489598        None   1
...       ...         ...  ..
1641  C568884        None   1
1642  C574897        None   1
1643  C577159        None   1
1644  C577394        None   1
1645  C579933        None   1

[1646 rows x 3 columns]

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT
        r.* EXCLUDE (WarehouseID),
        COALESCE(
            NULLIF(TRIM(r.WarehouseID), ''),
            (SELECT MAX(NULLIF(TRIM(r2.WarehouseID), ''))
             FROM retail_raw r2
             WHERE r2.Invoice = r.Invoice)
        ) AS WarehouseID
    FROM retail_clean r
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072707

In [ ]:
con.execute(""" SELECT * FROM retail_clean
WHERE WarehouseID IS NULL""").fetchdf()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PaymentMethod,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID,WarehouseID
0,246790,513282,35271S,None,-107,2010-06-23 13:35:00,united kingdom,OTHER,Other,Other,...,Bank transfer,CLEARANCE,0.2,Completed,11,Europe,Western Europe,GBP,GUEST,None
1,266111,C515125,M,Manual,-1,08/07/2010 14:14,germany,GIFT,Gifts,Occasions,...,Card,SPRING,0.05,Completed,5,Europe,Western Europe,EUR,12592.0,None
2,286570,517278,22487,damages,-16,2010-07-28 10:28:00,united kingdom,OTHER,Other,Other,...,Card,SPRING,0.05,Cancelled,15,Europe,Western Europe,GBP,GUEST,None
3,718970,C553536,23173,REGENCY TEAPOT ROSES,-2,2011-05-17 15:24:00,united kingdom,KITCHEN,Kitchenware,Interior,...,Bank transfer,WELCOME10,0.1,Completed,1,Europe,Western Europe,GBP,14051.0,None
4,721907,553847,84997C,CHILDRENS CUTLERY POLKADOT BLUE,4,2011-05-19 12:41:00,united kingdom,CHILD,Children,Occasions,...,PayPal,WELCOME10,0.1,Completed,5,Europe,Western Europe,GBP,15738.0,None
5,760224,557596,23114,Damaged,-1440,2011-06-21 11:33:00,united kingdom,OTHER,Other,Other,...,Card,SPRING,0.05,Completed,7,Europe,Western Europe,GBP,GUEST,None
6,1042022,C579933,22423,REGENCY CAKESTAND 3 TIER,-1,2011-12-01 09:44:00,united kingdom,KITCHEN,Kitchenware,Interior,...,Card,CLEARANCE,0.2,Completed,13,Europe,Western Europe,GBP,14853.0,None
7,346363,C523107,84405A,S/3 PINK COL METAL BASKET W HANDLE,-1,2010-09-20 12:26:00,united kingdom,OTHER,Other,Other,...,PayPal,WELCOME10,0.1,Completed,9,Europe,Western Europe,GBP,16919.0,None
8,386462,526520,21432,None,1,2010-10-12 11:13:00,united kingdom,OTHER,Other,Other,...,Invoice,CLEARANCE,0.2,Returned,15,Europe,Western Europe,GBP,GUEST,None
9,400020,527684,85031B,None,4,2010-10-18 14:53:00,united kingdom,OTHER,Other,Other,...,Invoice,XMAS,0.15,Completed,15,Europe,Western Europe,GBP,GUEST,None
10,429106,530370,16202b,None,20,2010-11-02 16:11:00,united kingdom,OTHER,Other,Other,...,PayPal,CLEARANCE,None,Completed,2,Europe,Western Europe,GBP,GUEST,None
11,832027,C563773,22730,ALARM CLOCK BAKELIKE IVORY,-8,2011-08-19 11:18:00,united kingdom,OTHER,Other,Other,...,Card,CLEARANCE,0.2,Completed,1,Europe,Western Europe,GBP,13048.0,None
12,835519,564163,22988,SOLDIERS EGG CUP,12,2011-08-23 13:28:00,united kingdom,OTHER,Other,Other,...,Invoice,WELCOME10,0.1,Completed,5,Europe,Western Europe,GBP,13481.0,None
13,868644,C566945,22178,VICTORIAN GLASS HANGING T-LIGHT,-6,2011-09-15 16:26:00,united kingdom,HOME,Home decoration,Interior,...,PayPal,NONE,0.0,Completed,9,Europe,Western Europe,GBP,13319.0,None
14,873931,C567440,22424,ENAMEL BREAD BIN CREAM,-1,2011-09-20 11:58:00,united kingdom,OTHER,Other,Other,...,Bank transfer,CLEARANCE,0.2,Completed,5,Europe,Western Europe,GBP,17841.0,None
15,924329,571259,21787,RAIN PONCHO RETROSPOT,360,2011-10-16 10:19:00,united kingdom,OTHER,Other,Other,...,Bank transfer,NONE,0.0,Completed,6,Europe,Western Europe,GBP,12901.0,None
16,149405,503599,16156S,WRAP PINK FAIRY CAKES,150,2010-04-06 09:37:00,united kingdom,KITCHEN,Kitchenware,Interior,...,Card,SPRING,0.05,Cancelled,2,Europe,Western Europe,GBP,17949.0,None
17,179274,C506390,22617,BAKING SET SPACEBOY DESIGN,-1,2010-04-29 12:57:00,united kingdom,HOME,Home decoration,Interior,...,PayPal,XMAS,0.15,Completed,7,Europe,Western Europe,GBP,16099.0,None
18,600703,542565,84664,None,-1,2011-01-28 14:52:00,united kingdom,OTHER,Other,Other,...,Invoice,WELCOME10,0.1,Completed,5,Europe,Western Europe,GBP,GUEST,None
19,680601,C549968,22151,PLACE SETTING WHITE HEART,-432,2011-04-13 14:24:00,united kingdom,HOME,Home decoration,Interior,...,Invoice,WELCOME10,0.1,Cancelled,5,Europe,Western Europe,GBP,14064.0,None
20,56845,C494489,22139,RETRO SPOT TEA SET CERAMIC 11 PC,-1,2010-01-14 17:14:00,united kingdom,KITCHEN,Kitchenware,Interior,...,PayPal,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP,15810.0,None
21,87370,497589,21034,REX CASH+CARRY JUMBO SHOPPER,1,2010-02-10 17:19:00,united kingdom,OTHER,Other,Other,...,Card,NONE,0.0,Completed,15,Europe,Western Europe,GBP,17377.0,None
22,564401,C539601,22768,FAMILY PHOTO FRAME CORNICE,-2,2010-12-20 13:58:00,united kingdom,HOME,Home decoration,Interior,...,Bank transfer,XMAS,0.15,Completed,6,Europe,Western Europe,GBP,14119.0,None
23,799640,560889,84789,None,1,2011-07-21 16:42:00,united kingdom,OTHER,Other,Other,...,Card,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP,GUEST,None
24,971896,C574897,AMAZONFEE,AMAZON FEE,-1,2011-11-07 15:03:00,united kingdom,OTHER,Other,Other,...,Card,CLEARANCE,0.2,Completed,4,Europe,Western Europe,GBP,GUEST,None
25,973778,575048,84665,water damaged,-15,2011-11-08 12:12:00,united kingdom,OTHER,Other,Other,...,PayPal,CLEARANCE,0.2,Completed,7,Europe,Western Europe,GBP,GUEST,None

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT *

REPLACE (
          COALESCE(NULLIF(TRIM(WarehouseID), ''), 'WH-UK-02') AS WarehouseID)
  FROM retail_clean
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072707

In [ ]:
con.execute(""" SELECT * FROM retail_clean
WHERE WarehouseID IS NULL""").fetchdf()

Empty DataFrame
Columns: [OrderLineID, Invoice, StockCode, Description, Quantity, InvoiceDate, Country, ProductCategoryCode, ProductCategory, ProductFamily, ProductNameClean, UnitPriceGBP, UnitCostGBP, CustomerSegment, CustomerType, LoyaltyProgram, SalesChannel, PaymentMethod, PromotionCode, DiscountRate, OrderStatus, DeliveryTime, Continent, Region, Currency, CustomerID, WarehouseID]
Index: []

[0 rows x 27 columns]

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT *
    REPLACE (
          REPLACE(Quantity, ' ', '') AS Quantity)
  FROM retail_clean
""").fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072707

In [ ]:
con.execute(""" SELECT Quantity FROM retail_clean""").fetchdf()

        Quantity
0              1
1              1
2              1
3              1
4              2
...          ...
1072702        1
1072703        1
1072704        1
1072705        1
1072706        1

[1072707 rows x 1 columns]

In [ ]:
con.execute("""
    SELECT *
    FROM retail_clean
    WHERE REGEXP_MATCHES(CAST(Quantity AS VARCHAR), '[a-zA-Z]')
    LIMIT 20
""").fetchdf()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PaymentMethod,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID,WarehouseID
0,245032,513101,84978,HANGING HEART JAR T-LIGHT HOLDER,12units,2010-06-21 15:51:00,united kingdom,HOME,Home decoration,Interior,...,Invoice,WELCOME10,0.1,Cancelled,11,Europe,Western Europe,GBP,16860.0,WH-UK-02
1,245033,513101,21681,GIANT MEDINA STAMPED METAL BOWL,2units,2010-06-21 15:51:00,united kingdom,KITCHEN,Kitchenware,Interior,...,Invoice,WELCOME10,0.1,Cancelled,11,Europe,Western Europe,GBP,16860.0,WH-UK-02
2,245083,513108,84581,DOG TOY WITH PINK CROCHET SKIRT,1units,2010-06-21 16:04:00,united kingdom,CHILD,Children,Occasions,...,Card,SPRING,0.05,Completed,3,Europe,Western Europe,GBP,14204.0,WH-UK-01
3,245115,513108,84625C,BLUE NEW BAROQUE CANDLESTICK CANDLE,2units,2010-06-21 16:04:00,united kingdom,HOME,Home decoration,Interior,...,Card,SPRING,0.05,Completed,3,Europe,Western Europe,GBP,14204.0,WH-UK-01
4,245253,513112,21636,MADRAS NOTEBOOK MEDIUM,4units,2010-06-21 16:28:00,united kingdom,STATIONERY,Stationery,Office,...,Bank transfer,XMAS,0.15,Completed,9,Europe,Western Europe,GBP,17338.0,WH-UK-01
5,245718,513190,85034C,3 ROSE MORRIS BOXED CANDLES,1units,2010-06-22 14:21:00,united kingdom,HOME,Home decoration,Interior,...,Invoice,XMAS,0.15,Completed,15,Europe,Western Europe,GBP,16894.0,WH-UK-02
6,245812,513190,21617,4 LILY BOTANICAL DINNER CANDLES,2units,2010-06-22 14:21:00,united kingdom,HOME,Home decoration,Interior,...,Invoice,XMAS,0.15,Completed,15,Europe,Western Europe,GBP,16894.0,WH-UK-02
7,245894,513191,22627,MINT KITCHEN SCALES,2units,2010-06-22 14:23:00,united kingdom,KITCHEN,Kitchenware,Interior,...,PayPal,WELCOME10,0.1,Completed,8,Europe,Western Europe,GBP,15809.0,WH-UK-02
8,245998,513199,22437,SET OF 9 BLACK SKULL BALLOONS,10units,2010-06-22 16:21:00,united kingdom,OTHER,Other,Other,...,Card,XMAS,0.15,Completed,3,Europe,Western Europe,GBP,GUEST,WH-UK-01
9,246049,513199,22028,PENNY FARTHING BIRTHDAY CARD,1units,2010-06-22 16:21:00,united kingdom,STATIONERY,Stationery,Office,...,Card,XMAS,0.15,Completed,3,Europe,Western Europe,GBP,GUEST,WH-UK-01
10,246140,513200,47593B,SCOTTIES DESIGN BABY BIB,2units,2010-06-22 16:28:00,united kingdom,CHILD,Children,Occasions,...,Bank transfer,SPRING,0.05,Completed,2,Europe,Western Europe,GBP,GUEST,WH-UK-01
11,246310,513203,48194,DOOR MAT HEARTS,4units,2010-06-23 08:14:00,ireland,HOME,Home decoration,Interior,...,Invoice,XMAS,0.15,Completed,9,Europe,Western Europe,EUR,14911.0,WH-EU-02
12,246725,513279,15036,ASSORTED COLOURS SILK FAN,24units,2010-06-23 13:19:00,united kingdom,OTHER,Other,Other,...,PayPal,WELCOME10,0.1,Completed,5,Europe,Western Europe,GBP,16180.0,WH-UK-02
13,246838,513292,20982,12 PENCILS TALL TUBE SKULLS,12units,2010-06-23 14:14:00,united kingdom,STATIONERY,Stationery,Office,...,Bank transfer,XMAS,0.15,Completed,5,Europe,Western Europe,GBP,14621.0,WH-UK-01
14,246864,513305,21355,TOAST ITS - I LOVE YOU,12units,2010-06-23 14:34:00,united kingdom,OTHER,Other,Other,...,Card,XMAS,0.15,Completed,9,Europe,Western Europe,GBP,15248.0,WH-UK-01
15,246943,513308,85066,CREAM SWEETHEART MINI CHEST,1units,2010-06-23 14:49:00,united kingdom,HOME,Home decoration,Interior,...,Bank transfer,SPRING,0.05,Completed,7,Europe,Western Europe,GBP,GUEST,WH-UK-01
16,247031,513308,22227,"DECORATION, HANGING HEART+MIRROR",1units,2010-06-23 14:49:00,united kingdom,HOME,Home decoration,Interior,...,Bank transfer,SPRING,0.05,Completed,7,Europe,Western Europe,GBP,GUEST,WH-UK-01
17,247353,513328,22556,PLASTERS IN TIN CIRCUS PARADE,1units,2010-06-23 17:16:00,united kingdom,OTHER,Other,Other,...,Card,CLEARANCE,0.2,Completed,8,Europe,Western Europe,GBP,GUEST,WH-UK-01
18,247475,513330,21721,CANDY SHOP STICKER SHEET,10units,2010-06-23 17:28:00,united kingdom,OTHER,Other,Other,...,PayPal,XMAS,0.15,Completed,15,Europe,Western Europe,GBP,17092.0,WH-UK-02
19,247914,513356,84988,SET OF 72 PINK HEART PAPER DOILIES,2units,2010-06-24 11:31:00,united kingdom,STATIONERY,Stationery,Office,...,Bank transfer,SPRING,0.05,Completed,5,Europe,Western Europe,GBP,GUEST,WH-UK-01

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * REPLACE (
        ABS(TRY_CAST(REPLACE(REPLACE(Quantity, 'units', ''), ' ', '') AS INTEGER)) AS Quantity
    )
    FROM retail_clean
""")

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * REPLACE (
          ABS(TRY_CAST(Quantity AS INTEGER)) AS Quantity)
  FROM retail_clean
""")

In [ ]:
con.execute("""DESCRIBE retail_clean""").df()

            column_name column_type null   key default extra
0           OrderLineID     VARCHAR  YES  None    None  None
1               Invoice     VARCHAR  YES  None    None  None
2             StockCode     VARCHAR  YES  None    None  None
3           Description     VARCHAR  YES  None    None  None
4              Quantity     INTEGER  YES  None    None  None
5           InvoiceDate     VARCHAR  YES  None    None  None
6               Country     VARCHAR  YES  None    None  None
7   ProductCategoryCode     VARCHAR  YES  None    None  None
8       ProductCategory     VARCHAR  YES  None    None  None
9         ProductFamily     VARCHAR  YES  None    None  None
10     ProductNameClean     VARCHAR  YES  None    None  None
11         UnitPriceGBP     VARCHAR  YES  None    None  None
12          UnitCostGBP     VARCHAR  YES  None    None  None
13      CustomerSegment     VARCHAR  YES  None    None  None
14         CustomerType     VARCHAR  YES  None    None  None
15       LoyaltyProgram     VARCHAR  YES  None    None  None
16         SalesChannel     VARCHAR  YES  None    None  None
17        PaymentMethod     VARCHAR  YES  None    None  None
18        PromotionCode     VARCHAR  YES  None    None  None
19         DiscountRate     VARCHAR  YES  None    None  None
20          OrderStatus     VARCHAR  YES  None    None  None
21         DeliveryTime     VARCHAR  YES  None    None  None
22            Continent     VARCHAR  YES  None    None  None
23               Region     VARCHAR  YES  None    None  None
24             Currency     VARCHAR  YES  None    None  None
25           CustomerID     VARCHAR  YES  None    None  None
26          WarehouseID     VARCHAR  YES  None    None  None

In [ ]:
con.execute("""SELECT Quantity FROM retail_clean""").df()

         Quantity
0               1
1               1
2               1
3               1
4               2
...           ...
1072702         1
1072703         1
1072704         1
1072705         1
1072706         1

[1072707 rows x 1 columns]

In [ ]:
con.execute("""SELECT * FROM retail_clean
WHERE Quantity = 99999 """).df()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PaymentMethod,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID,WarehouseID
0,246726,513279,22064,PINK DOUGHNUT TRINKET POT,99999,2010-06-23 13:19:00,united kingdom,OTHER,Other,Other,...,PayPal,WELCOME10,0.1,Completed,5,Europe,Western Europe,GBP,16180.0,WH-UK-02
1,247574,513335,48184,DOOR MAT ENGLISH ROSE,99999,2010-06-24 09:49:00,united kingdom,OTHER,Other,Other,...,Card,CLEARANCE,0.2,Completed,12,Europe,Western Europe,GBP,17686.0,WH-UK-01
2,249320,513539,40016,CHINESE DRAGON PAPER LANTERNS,99999,2010-06-25 11:27:00,united kingdom,STATIONERY,Stationery,Office,...,Bank transfer,WELCOME10,0.1,Completed,7,Europe,Western Europe,GBP,15674.0,WH-UK-01
3,251069,513620,21673,WHITE SPOT BLUE CERAMIC DRAWER KNOB,99999,2010-06-27 12:51:00,united kingdom,OTHER,Other,Other,...,PayPal,CLEARANCE,0.2,Cancelled,12,Europe,Western Europe,GBP,14532.0,WH-UK-02
4,251346,513627,22563,HAPPY STENCIL CRAFT,99999,2010-06-27 13:16:00,united kingdom,OTHER,Other,Other,...,Bank transfer,SPRING,0.05,Completed,1,Europe,Western Europe,GBP,17194.0,WH-UK-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,1009426,577517,23493,VINTAGE DOILY TRAVEL SEWING KIT,99999,2011-11-20 13:16:00,united kingdom,OTHER,Other,Other,...,PayPal,NONE,0.0,Completed,15,Europe,Western Europe,GBP,16710.0,WH-UK-02
649,1010033,577534,72130,COLUMBIAN CANDLE ROUND,99999,2011-11-20 14:05:00,united kingdom,HOME,Home decoration,Interior,...,Bank transfer,WELCOME10,0.1,Completed,10,Europe,Western Europe,GBP,18127.0,WH-UK-01
650,1012697,577768,21889,WOODEN BOX OF DOMINOES,99999,2011-11-21 15:18:00,united kingdom,OTHER,Other,Other,...,Card,XMAS,0.15,Completed,11,Europe,Western Europe,GBP,GUEST,WH-UK-01
651,1013304,577782,20971,PINK BLUE FELT CRAFT TRINKET BOX,99999,2011-11-21 16:17:00,united kingdom,OTHER,Other,Other,...,Bank transfer,XMAS,0.15,Completed,13,Europe,Western Europe,GBP,16549.0,WH-UK-01
652,1013791,577812,21577,SAVE THE PLANET COTTON TOTE BAG,99999,2011-11-22 08:56:00,united kingdom,GIFT,Gifts,Occasions,...,Invoice,NONE,0.0,Completed,12,Europe,Western Europe,GBP,16956.0,WH-UK-02

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * REPLACE (
        CASE
            WHEN Quantity = 99999 THEN
                MEDIAN(CASE WHEN Quantity != 99999 THEN Quantity END) OVER (PARTITION BY StockCode)
            ELSE Quantity
        END AS Quantity
    )
    FROM retail_clean
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [ ]:
con.execute("""
    SELECT COUNT(*) AS nb_99999_restants
    FROM retail_clean
    WHERE Quantity = 99999
""").fetchdf()

   nb_99999_restants
0                  0

In [ ]:
con.execute("""SELECT Quantity FROM retail_clean
""").df()

         Quantity
0             3.0
1             4.0
2             1.0
3             1.0
4             1.0
...           ...
1072702       1.0
1072703      10.0
1072704       1.0
1072705       1.0
1072706       1.0

[1072707 rows x 1 columns]

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT *
EXCLUDE (ProductNameClean),
      COALESCE(
          NULLIF(TRIM(ProductNameClean), ''),
          MAX(NULLIF(TRIM(ProductNameClean), '')) OVER (PARTITION BY StockCode)) AS ProductNameClean
  FROM retail_clean
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072707

In [ ]:
con.execute("""SELECT ProductNameClean FROM retail_clean
WHERE ProductNameClean IS NULL""").df()

    ProductNameClean
0               None
1               None
2               None
3               None
4               None
..               ...
364             None
365             None
366             None
367             None
368             None

[369 rows x 1 columns]

In [ ]:
con.execute("""
    SELECT StockCode, COUNT(*) AS nb
    FROM retail_clean
    WHERE ProductNameClean IS NULL
    GROUP BY StockCode
    ORDER BY nb DESC
""").fetchdf()

        StockCode  nb
0           21502   2
1    gift_0001_60   2
2    gift_0001_90   2
3          84933D   2
4          37477D   2
..            ...  ..
357         37504   1
358        79302C   1
359         20883   1
360         21020   1
361         21273   1

[362 rows x 2 columns]

In [ ]:
con.execute("""SELECT * FROM retail_clean
WHERE ProductNameCLean IS NULL""").df()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID,WarehouseID,ProductNameClean
0,71558,495877,16169H,None,64.0,2010-01-27 11:33:00,united kingdom,OTHER,Other,Other,...,SPRING,0.05,Completed,15,Europe,Western Europe,GBP,GUEST,WH-UK-02,None
1,80582,496780,16248A,None,3.0,2010-02-03 15:59:00,united kingdom,OTHER,Other,Other,...,SPRING,0.05,Completed,7,Europe,Western Europe,GBP,GUEST,WH-UK-02,None
2,210985,509776,20690,None,3.0,2010-05-25 16:50:00,united kingdom,OTHER,Other,Other,...,NONE,0.0,Completed,2,Europe,Western Europe,GBP,GUEST,WH-UK-01,None
3,80584,496782,21227,None,3.0,2010-02-03 16:02:00,united kingdom,OTHER,Other,Other,...,SPRING,0.05,Completed,14,Europe,Western Europe,GBP,GUEST,WH-UK-01,None
4,100249,498860,21778,None,25.0,2010-02-23 12:22:00,united kingdom,OTHER,other,Other,...,CLEARANCE,0.2,Returned,5,Europe,Western Europe,GBP,GUEST,WH-UK-01,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,80953,496813,85105,None,3.0,2010-02-04 09:45:00,united kingdom,OTHER,Other,Other,...,WELCOME10,0.1,Returned,4,Europe,Western Europe,GBP,GUEST,WH-UK-01,None
365,44620,493299,85184A,None,1.0,2009-12-22 15:17:00,united kingdom,OTHER,Other,Other,...,NONE,0.0,Completed,15,Europe,Western Europe,GBP,GUEST,WH-UK-01,None
366,80597,496798,90197A,None,2.0,2010-02-03 16:50:00,united kingdom,OTHER,Other,Other,...,XMAS,0.15,Completed,12,Europe,Western Europe,GBP,GUEST,WH-UK-02,None
367,80362,496746,DCGS0039,None,1.0,2010-02-03 14:36:00,united kingdom,OTHER,Other,Other,...,XMAS,0.15,Completed,10,Europe,Western Europe,GBP,GUEST,WH-UK-02,None
368,101694,499042,DCGSLGIRL,None,57.0,2010-02-24 13:31:00,united kingdom,OTHER,Other,Other,...,NONE,0.0,Completed,9,Europe,Western Europe,GBP,GUEST,WH-UK-01,None

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT *
    FROM retail_clean
    WHERE ProductNameClean IS NOT NULL
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072338

In [ ]:
import pandas as pd

colonnes_clean = con.execute("DESCRIBE retail_clean").fetchdf()['column_name'].tolist()
total_clean = con.execute("SELECT COUNT(*) FROM retail_clean").fetchone()[0]

audit_clean = []
for col in colonnes_clean:
    nb_manquants_clean = con.execute(f"SELECT COUNT(*) - COUNT({col}) FROM retail_clean").fetchone()[0]
    audit_clean.append({'colonne_clean': col, 'nb_manquants_clean': nb_manquants_clean})

audit_df_clean = pd.DataFrame(audit_clean).sort_values('nb_manquants_clean', ascending=False)
audit_df_clean

          colonne_clean  nb_manquants_clean
3           Description               12624
8       ProductCategory                4340
15         SalesChannel                4194
7   ProductCategoryCode                3224
17        PromotionCode                1776
23             Currency                1673
19          OrderStatus                1334
11          UnitCostGBP                1044
20         DeliveryTime                 815
18         DiscountRate                 635
4              Quantity                   1
10         UnitPriceGBP                   0
9         ProductFamily                   0
5           InvoiceDate                   0
6               Country                   0
1               Invoice                   0
0           OrderLineID                   0
2             StockCode                   0
14       LoyaltyProgram                   0
16        PaymentMethod                   0
12      CustomerSegment                   0
13         CustomerType                   0
21            Continent                   0
22               Region                   0
24           CustomerID                   0
25          WarehouseID                   0
26     ProductNameClean                   0

In [ ]:
con.execute("""
    SELECT StockCode, COUNT(*) AS nb_lignes,
           COUNT(DISTINCT ProductCategory) AS nb_categories_distinctes,
           SUM(CASE WHEN ProductCategory IS NULL THEN 1 ELSE 0 END) AS nb_vides
    FROM retail_clean
    GROUP BY StockCode
    HAVING nb_vides > 0
    ORDER BY nb_vides DESC
    LIMIT 20
""").fetchdf()

   StockCode  nb_lignes  nb_categories_distinctes  nb_vides
0     85123A       5806                         3      28.0
1      20725       3269                         2      18.0
2     85099B       4197                         3      18.0
3      22423       4448                         3      17.0
4      84879       2971                         2      16.0
5      22382       2261                         2      11.0
6      21080       2235                         2      11.0
7      22993       1115                         2      11.0
8      22411       2304                         2      11.0
9      21210       1207                         3      11.0
10     21931       2444                         2      10.0
11     22386       2359                         2      10.0
12     21181       1926                         3      10.0
13     22666       1821                         2      10.0
14         M       1416                         2       9.0
15     21671        773                         2       9.0
16     21034       2211                         2       9.0
17     21212       3340                         2       9.0
18     22662       1049                         2       9.0
19     22900        822                         3       9.0

In [ ]:
con.execute("""
    SELECT StockCode, ProductCategory, COUNT(*) AS nb
    FROM retail_clean
    WHERE StockCode = '85123A'
    GROUP BY StockCode, ProductCategory
""").fetchdf()

  StockCode  ProductCategory    nb
0    85123A  Home decoration  5749
1    85123A             None    28
2    85123A  home decoration    26
3    85123A            Other     3

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * REPLACE (
        LOWER(TRIM(ProductCategory)) AS ProductCategory
    )
    FROM retail_clean
""").df()

     Count
0  1072338

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE retail_clean AS
    SELECT * REPLACE (
        COALESCE(
            NULLIF(TRIM(ProductCategory), ''),
            MAX(NULLIF(TRIM(ProductCategory), '')) OVER (PARTITION BY StockCode)
        ) AS ProductCategory
    )
    FROM retail_clean
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

     Count
0  1072338

In [ ]:
import pandas as pd

colonnes_clean = con.execute("DESCRIBE retail_clean").fetchdf()['column_name'].tolist()
total_clean = con.execute("SELECT COUNT(*) FROM retail_clean").fetchone()[0]

audit_clean = []
for col in colonnes_clean:
    nb_manquants_clean = con.execute(f"SELECT COUNT(*) - COUNT({col}) FROM retail_clean").fetchone()[0]
    audit_clean.append({'colonne_clean': col, 'nb_manquants_clean': nb_manquants_clean})

audit_df_clean = pd.DataFrame(audit_clean).sort_values('nb_manquants_clean', ascending=False)
audit_df_clean

          colonne_clean  nb_manquants_clean
3           Description               12624
15         SalesChannel                4194
7   ProductCategoryCode                3224
17        PromotionCode                1776
23             Currency                1673
19          OrderStatus                1334
11          UnitCostGBP                1044
20         DeliveryTime                 815
18         DiscountRate                 635
4              Quantity                   1
2             StockCode                   0
10         UnitPriceGBP                   0
9         ProductFamily                   0
8       ProductCategory                   0
6               Country                   0
5           InvoiceDate                   0
0           OrderLineID                   0
1               Invoice                   0
14       LoyaltyProgram                   0
16        PaymentMethod                   0
12      CustomerSegment                   0
13         CustomerType                   0
21            Continent                   0
22               Region                   0
24           CustomerID                   0
25          WarehouseID                   0
26     ProductNameClean                   0

In [ ]:
con.execute(""" SELECT ProductCategory, ProductCategoryCode FROM retail_clean
WHERE ProductCategoryCode IS NULL""").df()

      ProductCategory ProductCategoryCode
0     home decoration                None
1               other                None
2            children                None
3            children                None
4               other                None
...               ...                 ...
3219            other                None
3220            other                None
3221            other                None
3222            other                None
3223            other                None

[3224 rows x 2 columns]

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE retail_clean AS
SELECT * REPLACE (
    TRY_CAST(InvoiceDate AS TIMESTAMP) AS InvoiceDate
)
FROM retail_clean;
""").df()

     Count
0  1072338

In [ ]:
con.execute("""DESCRIBE retail_clean""").df()

            column_name column_type null   key default extra
0           OrderLineID     VARCHAR  YES  None    None  None
1               Invoice     VARCHAR  YES  None    None  None
2             StockCode     VARCHAR  YES  None    None  None
3           Description     VARCHAR  YES  None    None  None
4              Quantity      DOUBLE  YES  None    None  None
5           InvoiceDate   TIMESTAMP  YES  None    None  None
6               Country     VARCHAR  YES  None    None  None
7   ProductCategoryCode     VARCHAR  YES  None    None  None
8       ProductCategory     VARCHAR  YES  None    None  None
9         ProductFamily     VARCHAR  YES  None    None  None
10         UnitPriceGBP     VARCHAR  YES  None    None  None
11          UnitCostGBP     VARCHAR  YES  None    None  None
12      CustomerSegment     VARCHAR  YES  None    None  None
13         CustomerType     VARCHAR  YES  None    None  None
14       LoyaltyProgram     VARCHAR  YES  None    None  None
15         SalesChannel     VARCHAR  YES  None    None  None
16        PaymentMethod     VARCHAR  YES  None    None  None
17        PromotionCode     VARCHAR  YES  None    None  None
18         DiscountRate     VARCHAR  YES  None    None  None
19          OrderStatus     VARCHAR  YES  None    None  None
20         DeliveryTime     VARCHAR  YES  None    None  None
21            Continent     VARCHAR  YES  None    None  None
22               Region     VARCHAR  YES  None    None  None
23             Currency     VARCHAR  YES  None    None  None
24           CustomerID     VARCHAR  YES  None    None  None
25          WarehouseID     VARCHAR  YES  None    None  None
26     ProductNameClean     VARCHAR  YES  None    None  None

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE retail_clean AS
SELECT * REPLACE (
    CAST(InvoiceDate AS DATE) AS InvoiceDate
)
FROM retail_clean;
""").df()

     Count
0  1072338

In [ ]:
con.execute(""" SELECT InvoiceDate FROM retail_clean""").df()

        InvoiceDate
0        2010-09-23
1        2011-04-26
2        2011-07-22
3        2011-05-31
4        2011-08-08
...             ...
1072333  2010-12-20
1072334  2010-08-09
1072335  2010-08-10
1072336  2010-10-21
1072337  2011-07-27

[1072338 rows x 1 columns]

In [ ]:
con.execute("""SELECT StockCode,ProductNameClean, COUNT (*) AS nb
    FROM retail_clean
    GROUP BY StockCode,ProductNameClean""").df()

     StockCode                     ProductNameClean   nb
0       15058C      Ice Cream Design Garden Parasol  125
1       15058C                            Wet/Rusty    1
2        16044             Pop-Art Fluorescent Pens    6
3        16054    Popart Rect Pencil Sharpener Asst   40
4       16161C                    Wrap Speed Demons    5
...        ...                                  ...  ...
6840     21823                        Amazon Adjust    1
6841     21833                              Damages    1
6842     21878  Pack Of 6 Sandcastle Flags Assorted  429
6843     21933      Pink Vintage Paisley Picnic Bag  659
6844     21943     Cakes And Rabbits Design Flannel  152

[6845 rows x 3 columns]

In [ ]:
con.execute("""
    UPDATE retail_clean
    SET StockCode = UPPER(StockCode)
""")

# Vérification rapide
result = con.sql("""
    SELECT StockCode, COUNT(*) AS nb
    FROM retail_clean
    GROUP BY StockCode
    ORDER BY StockCode
    LIMIT 20
""").fetchdf()

result

   StockCode    nb
0      10002   400
1     10002R     3
2      10080    31
3      10109     2
4      10120    79
5     10123C    71
6     10123G    21
7     10124A    20
8     10124G    11
9      10125   181
10     10133   303
11     10134    59
12     10135   344
13     10138    28
14     11001   279
15     15002     1
16     15030    28
17     15034   271
18     15036  1023
19     15039   317

In [ ]:
# Nombre de StockCode distincts avant/après devrait avoir diminué si des doublons de casse existaient
nb_distinct = con.sql("SELECT COUNT(DISTINCT StockCode) AS nb FROM retail_clean").fetchdf()
print(nb_distinct)

     nb
0  4779

In [ ]:
diagnostic = con.sql("""
    WITH freq AS (
        SELECT StockCode, ProductNameClean, COUNT(*) AS nb,
               RANK() OVER (PARTITION BY StockCode ORDER BY COUNT(*) DESC) AS rang
        FROM retail_clean
        WHERE ProductNameClean IS NOT NULL
        GROUP BY StockCode, ProductNameClean
    ),
    stockcodes_multi_noms AS (
        SELECT StockCode, COUNT(*) AS nb_noms_distincts
        FROM freq
        GROUP BY StockCode
        HAVING COUNT(*) > 1
    ),
    stockcodes_egalite AS (
        SELECT StockCode
        FROM freq
        WHERE rang = 1
        GROUP BY StockCode
        HAVING COUNT(*) > 1
    )
    SELECT
        (SELECT COUNT(*) FROM stockcodes_multi_noms) AS nb_stockcode_avec_plusieurs_noms,
        (SELECT COUNT(*) FROM stockcodes_egalite) AS nb_stockcode_avec_egalite_frequence
""").fetchdf()

diagnostic

   nb_stockcode_avec_plusieurs_noms  nb_stockcode_avec_egalite_frequence
0                              1188                                    7

In [ ]:
con.execute("""
    UPDATE retail_clean AS r
    SET ProductNameClean = nb_occurrences.ProductNameClean
    FROM (
        SELECT
            StockCode,
            ProductNameClean,
            RANK() OVER (PARTITION BY StockCode ORDER BY COUNT(*) DESC) AS rang_frequence
        FROM retail_clean
        WHERE ProductNameClean IS NOT NULL
        GROUP BY StockCode, ProductNameClean
    ) AS nb_occurrences
    WHERE r.StockCode = nb_occurrences.StockCode
      AND nb_occurrences.rang_frequence = 1
      AND r.StockCode NOT IN (
          SELECT StockCode FROM (
              SELECT StockCode, RANK() OVER (PARTITION BY StockCode ORDER BY COUNT(*) DESC) AS rang_frequence
              FROM retail_clean WHERE ProductNameClean IS NOT NULL
              GROUP BY StockCode, ProductNameClean
          ) sub WHERE rang_frequence = 1
          GROUP BY StockCode HAVING COUNT(*) > 1
      )
""")

In [ ]:
egalites = con.sql("""
    WITH freq AS (
        SELECT StockCode, ProductNameClean, COUNT(*) AS nb,
               RANK() OVER (PARTITION BY StockCode ORDER BY COUNT(*) DESC) AS rang
        FROM retail_clean
        WHERE ProductNameClean IS NOT NULL
        GROUP BY StockCode, ProductNameClean
    )
    SELECT StockCode, ProductNameClean, nb
    FROM freq
    WHERE StockCode IN (
        SELECT StockCode FROM freq WHERE rang = 1
        GROUP BY StockCode HAVING COUNT(*) > 1
    )
    AND rang = 1
    ORDER BY StockCode, ProductNameClean
""").fetchdf()

egalites

   StockCode                     ProductNameClean   nb
0     16151A      Flowers Handbag Blue And Orange    3
1     16151A                                Found    3
2     17027A              Incense Bazaar Cannabis    2
3     17027A                              Missing    2
4      21701                             No Stock    1
5      21701  Set 6 Mini Sushi Set Fridge Magnets    1
6      22135                Ladle Love Heart Pink  167
7      22135           Mini Ladle Love Heart Pink  167
8      23595                           Adjustment    1
9      23595                        Re-Adjustment    1
10    84206B          Cat W Sunglasses Blank Card    1
11    84206B       Cat With Sunglasses Blank Card    1
12    84966C          Green Kashmiri Boxed Mirror    2
13    84966C                          Sold As A/B    2

In [ ]:
con.execute("""
    UPDATE retail_clean
    SET ProductNameClean = CASE StockCode
        WHEN '16151A' THEN 'Flowers Handbag Blue And Orange'
        WHEN '17027A' THEN 'Incense Bazaar Cannabis'
        WHEN '21701'  THEN 'Set 6 Mini Sushi Set Fridge Magnets'
        WHEN '84966C' THEN 'Green Kashmiri Boxed Mirror'
        ELSE ProductNameClean
    END
    WHERE StockCode IN ('16151A', '17027A', '21701', '84966C')
""")

In [ ]:
verif = con.sql("""
    SELECT StockCode, ProductNameClean
    FROM retail_clean
    WHERE StockCode IN ('16151A', '17027A', '21701', '84966C')
    GROUP BY StockCode, ProductNameClean
""").fetchdf()

verif

  StockCode                     ProductNameClean
0     21701  Set 6 Mini Sushi Set Fridge Magnets
1    84966C          Green Kashmiri Boxed Mirror
2    17027A              Incense Bazaar Cannabis
3    16151A      Flowers Handbag Blue And Orange

In [ ]:
con.execute("""SELECT * FROM retail_clean
WHERE StockCode = '23595'""").df()

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,Country,ProductCategoryCode,ProductCategory,ProductFamily,...,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency,CustomerID,WarehouseID,ProductNameClean
0,942570,572615,23595,re-adjustment,5.0,2011-10-25,united kingdom,OTHER,other,Other,...,NONE,0.0,Cancelled,15,Europe,Western Europe,GBP,GUEST,WH-UK-01,Re-Adjustment
1,942569,572614,23595,adjustment,5.0,2011-10-25,united kingdom,OTHER,other,Other,...,NONE,0.0,Completed,1,Europe,Western Europe,GBP,GUEST,WH-UK-02,Adjustment

In [ ]:
con.execute("""
    DELETE FROM retail_clean
    WHERE StockCode = '23595'
""")

In [ ]:
apres = con.sql("SELECT COUNT(*) AS nb FROM retail_clean WHERE StockCode = '23595'").fetchdf()
print(f"Lignes restantes avec ce StockCode : {apres['nb'][0]}")  # doit être 0

Lignes restantes avec ce StockCode : 0

In [ ]:
con.execute("""
    UPDATE retail_clean
    SET ProductNameClean = CASE StockCode
        WHEN '22135'  THEN 'Ladle Love Heart Pink'
        WHEN '84206B' THEN 'Cat With Sunglasses Blank Card'
        ELSE ProductNameClean
    END
    WHERE StockCode IN ('22135','84206B')
""")

In [ ]:
verif = con.sql("""
    SELECT StockCode, COUNT(DISTINCT ProductNameClean) AS nb_noms_distincts
    FROM retail_clean
    WHERE ProductNameClean IS NOT NULL
    GROUP BY StockCode
    HAVING COUNT(DISTINCT ProductNameClean) > 1
""").fetchdf()

print(f"StockCode encore ambigus : {len(verif)}")
verif

StockCode encore ambigus : 0

Empty DataFrame
Columns: [StockCode, nb_noms_distincts]
Index: []

In [ ]:
schema = con.sql("DESCRIBE retail_clean").fetchdf()
schema

            column_name column_type null   key default extra
0           OrderLineID     VARCHAR  YES  None    None  None
1               Invoice     VARCHAR  YES  None    None  None
2             StockCode     VARCHAR  YES  None    None  None
3           Description     VARCHAR  YES  None    None  None
4              Quantity      DOUBLE  YES  None    None  None
5           InvoiceDate        DATE  YES  None    None  None
6               Country     VARCHAR  YES  None    None  None
7   ProductCategoryCode     VARCHAR  YES  None    None  None
8       ProductCategory     VARCHAR  YES  None    None  None
9         ProductFamily     VARCHAR  YES  None    None  None
10         UnitPriceGBP     VARCHAR  YES  None    None  None
11          UnitCostGBP     VARCHAR  YES  None    None  None
12      CustomerSegment     VARCHAR  YES  None    None  None
13         CustomerType     VARCHAR  YES  None    None  None
14       LoyaltyProgram     VARCHAR  YES  None    None  None
15         SalesChannel     VARCHAR  YES  None    None  None
16        PaymentMethod     VARCHAR  YES  None    None  None
17        PromotionCode     VARCHAR  YES  None    None  None
18         DiscountRate     VARCHAR  YES  None    None  None
19          OrderStatus     VARCHAR  YES  None    None  None
20         DeliveryTime     VARCHAR  YES  None    None  None
21            Continent     VARCHAR  YES  None    None  None
22               Region     VARCHAR  YES  None    None  None
23             Currency     VARCHAR  YES  None    None  None
24           CustomerID     VARCHAR  YES  None    None  None
25          WarehouseID     VARCHAR  YES  None    None  None
26     ProductNameClean     VARCHAR  YES  None    None  None

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_DATE AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY InvoiceDate) AS DateID,
        InvoiceDate AS Date,
        EXTRACT(YEAR FROM InvoiceDate) AS Year,
        EXTRACT(QUARTER FROM InvoiceDate) AS Quarter,
        EXTRACT(MONTH FROM InvoiceDate) AS Month,
        STRFTIME(InvoiceDate, '%B') AS MonthName,
        EXTRACT(WEEK FROM InvoiceDate) AS WeekOfYear,
        EXTRACT(DAY FROM InvoiceDate) AS Day,
        STRFTIME(InvoiceDate, '%A') AS DayName,
        EXTRACT(DOW FROM InvoiceDate) AS DayOfWeek,
        CASE WHEN EXTRACT(DOW FROM InvoiceDate) IN (0, 6) THEN TRUE ELSE FALSE END AS IsWeekend
    FROM (
        SELECT DISTINCT InvoiceDate
        FROM retail_clean
        WHERE InvoiceDate IS NOT NULL
    )
    ORDER BY InvoiceDate
""")

con.sql("SELECT * FROM DIM_DATE LIMIT 5").fetchdf()

,DateID,Date,Year,Quarter,Month,MonthName,WeekOfYear,Day,DayName,DayOfWeek,IsWeekend
0,1,2009-12-01,2009,4,12,December,49,1,Tuesday,2,False
1,2,2009-12-02,2009,4,12,December,49,2,Wednesday,3,False
2,3,2009-12-03,2009,4,12,December,49,3,Thursday,4,False
3,4,2009-12-04,2009,4,12,December,49,4,Friday,5,False
4,5,2009-12-05,2009,4,12,December,49,5,Saturday,6,True

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_PRODUCT AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY StockCode) AS ProductID,
        StockCode,
        ProductNameClean,
        Description,
        ProductCategoryCode,
        ProductCategory,
        ProductFamily
    FROM (
        SELECT DISTINCT
            StockCode,
            ProductNameClean,
            Description,
            ProductCategoryCode,
            ProductCategory,
            ProductFamily
        FROM retail_clean
        WHERE StockCode IS NOT NULL
    )
""")

con.sql("SELECT * FROM DIM_PRODUCT LIMIT 10").fetchdf()

,ProductID,StockCode,ProductNameClean,Description,ProductCategoryCode,ProductCategory,ProductFamily
0,1,10002,Inflatable Political Globe,INFLATABLE POLITICAL GLOBE,OTHER,other,Other
1,2,10002,Inflatable Political Globe,INFLATABLE POLITICAL GLOBE,OTHER,other,Other
2,3,10002,Inflatable Political Globe,INFLATABLE POLITICAL GLOBE,None,other,Other
3,4,10002,Inflatable Political Globe,None,OTHER,other,Other
4,5,10002R,Robot Pencil Sharpner,ROBOT PENCIL SHARPNER,STATIONERY,stationery,Office
5,6,10080,Groovy Cactus Inflatable,None,OTHER,other,Other
6,7,10080,Groovy Cactus Inflatable,GROOVY CACTUS INFLATABLE,OTHER,other,Other
7,8,10080,Groovy Cactus Inflatable,check,OTHER,other,Other
8,9,10109,Bendy Colour Pencils,BENDY COLOUR PENCILS,STATIONERY,stationery,Office
9,10,10109,Bendy Colour Pencils,None,OTHER,other,Other

In [ ]:
doublons_produit = con.sql("""
    SELECT StockCode, COUNT(*) AS nb_lignes
    FROM DIM_PRODUCT
    GROUP BY StockCode
    HAVING COUNT(*) > 1
    ORDER BY nb_lignes DESC
""").fetchdf()

print(f"Nombre de StockCode avec plusieurs lignes : {len(doublons_produit)}")
doublons_produit

Nombre de StockCode avec plusieurs lignes : 4348

         StockCode  nb_lignes
0            21181         15
1            20713         15
2           85099B         14
3            21843         12
4            22197         12
...            ...        ...
4343      DCGS0072          2
4344  GIFT_0001_10          2
4345  GIFT_0001_40          2
4346  GIFT_0001_50          2
4347       TEST002          2

[4348 rows x 2 columns]

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_PRODUCT AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY StockCode) AS ProductID,
        StockCode,
        ProductNameClean,
        ProductCategoryCode,
        ProductCategory,
        ProductFamily
    FROM (
        SELECT DISTINCT
            StockCode,
            ProductNameClean,
            ProductCategoryCode,
            ProductCategory,
            ProductFamily
        FROM retail_clean
        WHERE StockCode IS NOT NULL
    )
""")

doublons_produit = con.sql("""
    SELECT StockCode, COUNT(*) AS nb_lignes
    FROM DIM_PRODUCT
    GROUP BY StockCode
    HAVING COUNT(*) > 1
    ORDER BY nb_lignes DESC
""").fetchdf()

print(f"Nombre de StockCode avec plusieurs lignes : {len(doublons_produit)}")
doublons_produit

Nombre de StockCode avec plusieurs lignes : 2420

         StockCode  nb_lignes
0           16161P          5
1           85123A          5
2            21907          5
3            22457          5
4            22959          5
...            ...        ...
2415  GIFT_0001_20          2
2416  GIFT_0001_30          2
2417  GIFT_0001_70          2
2418  GIFT_0001_80          2
2419             S          2

[2420 rows x 2 columns]

In [ ]:
nb_stockcode = con.sql("SELECT COUNT(DISTINCT StockCode) AS nb FROM retail_clean").fetchdf()
print(f"Nombre de StockCode distincts : {nb_stockcode['nb'][0]}")

verif_colonnes = con.sql("""
    SELECT
        'ProductNameClean' AS colonne, COUNT(DISTINCT StockCode || '|' || COALESCE(ProductNameClean,'')) AS nb_combinaisons FROM retail_clean
    UNION ALL
    SELECT 'ProductCategoryCode', COUNT(DISTINCT StockCode || '|' || COALESCE(ProductCategoryCode,'')) FROM retail_clean
    UNION ALL
    SELECT 'ProductCategory', COUNT(DISTINCT StockCode || '|' || COALESCE(ProductCategory,'')) FROM retail_clean
    UNION ALL
    SELECT 'ProductFamily', COUNT(DISTINCT StockCode || '|' || COALESCE(ProductFamily,'')) FROM retail_clean
""").fetchdf()

verif_colonnes

Nombre de StockCode distincts : 4778

               colonne  nb_combinaisons
0     ProductNameClean             4778
1  ProductCategoryCode             7641
2      ProductCategory             5996
3        ProductFamily             5996

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_PRODUCT AS
    WITH categorie_frequente AS (
        SELECT
            StockCode,
            ProductCategoryCode,
            ProductCategory,
            ProductFamily,
            ROW_NUMBER() OVER (
                PARTITION BY StockCode
                ORDER BY COUNT(*) DESC, ProductCategoryCode ASC
            ) AS rn
        FROM retail_clean
        WHERE ProductCategoryCode IS NOT NULL
        GROUP BY StockCode, ProductCategoryCode, ProductCategory, ProductFamily
    ),
    nom_produit AS (
        SELECT DISTINCT StockCode, ProductNameClean
        FROM retail_clean
        WHERE StockCode IS NOT NULL
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY n.StockCode) AS ProductID,
        n.StockCode,
        n.ProductNameClean,
        c.ProductCategoryCode,
        c.ProductCategory,
        c.ProductFamily
    FROM nom_produit n
    LEFT JOIN categorie_frequente c
        ON n.StockCode = c.StockCode AND c.rn = 1
""")

con.sql("SELECT * FROM DIM_PRODUCT LIMIT 10").fetchdf()

,ProductID,StockCode,ProductNameClean,ProductCategoryCode,ProductCategory,ProductFamily
0,1,10002,Inflatable Political Globe,OTHER,other,Other
1,2,10002R,Robot Pencil Sharpner,STATIONERY,stationery,Office
2,3,10080,Groovy Cactus Inflatable,OTHER,other,Other
3,4,10109,Bendy Colour Pencils,OTHER,other,Other
4,5,10120,Doggy Rubber,OTHER,other,Other
5,6,10123C,Hearts Wrapping Tape,STATIONERY,stationery,Office
6,7,10123G,Army Camo Wrapping Tape,STATIONERY,stationery,Office
7,8,10124A,Spots On Red Bookcover Tape,STATIONERY,stationery,Office
8,9,10124G,Army Camo Bookcover Tape,STATIONERY,stationery,Office
9,10,10125,Mini Funky Design Tapes,STATIONERY,stationery,Office

In [ ]:
doublons_produit = con.sql("""
    SELECT StockCode, COUNT(*) AS nb_lignes
    FROM DIM_PRODUCT
    GROUP BY StockCode
    HAVING COUNT(*) > 1
""").fetchdf()

nb_total = con.sql("SELECT COUNT(*) AS nb FROM DIM_PRODUCT").fetchdf()

print(f"Nombre total de lignes dans DIM_PRODUCT : {nb_total['nb'][0]}")
print(f"StockCode encore en doublon : {len(doublons_produit)}")

Nombre total de lignes dans DIM_PRODUCT : 4778
StockCode encore en doublon : 0

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_CUSTOMER AS
    WITH segment_frequent AS (
        SELECT
            CustomerID,
            CustomerSegment,
            CustomerType,
            LoyaltyProgram,
            ROW_NUMBER() OVER (
                PARTITION BY CustomerID
                ORDER BY COUNT(*) DESC, CustomerSegment ASC
            ) AS rn
        FROM retail_clean
        WHERE CustomerID IS NOT NULL
        GROUP BY CustomerID, CustomerSegment, CustomerType, LoyaltyProgram
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY CustomerID) AS CustomerKey,
        CustomerID,
        CustomerSegment,
        CustomerType,
        LoyaltyProgram
    FROM segment_frequent
    WHERE rn = 1
""")

con.sql("SELECT * FROM DIM_CUSTOMER LIMIT 10").fetchdf()

   CustomerKey CustomerID CustomerSegment    CustomerType LoyaltyProgram
0            1    12346.0             VIP  Small business           Gold
1            2    12347.0           Loyal  Small business         Silver
2            3    12348.0             VIP        Retailer           Gold
3            4    12349.0         Regular        Retailer         Bronze
4            5    12350.0         Regular      Individual         Bronze
5            6    12351.0       Low value      Individual             No
6            7    12352.0       Low value  Small business             No
7            8    12353.0       Low value  Small business             No
8            9    12354.0       Low value        Retailer             No
9           10    12355.0           Loyal  Small business         Silver

In [ ]:
nb_customerid_distinct = con.sql("SELECT COUNT(DISTINCT CustomerID) AS nb FROM retail_clean WHERE CustomerID IS NOT NULL").fetchdf()
nb_dim = con.sql("SELECT COUNT(*) AS nb FROM DIM_CUSTOMER").fetchdf()

print(f"CustomerID distincts dans retail_clean : {nb_customerid_distinct['nb'][0]}")
print(f"Lignes dans DIM_CUSTOMER : {nb_dim['nb'][0]}")

doublons_client = con.sql("""
    SELECT CustomerID, COUNT(*) AS nb_lignes
    FROM DIM_CUSTOMER
    GROUP BY CustomerID
    HAVING COUNT(*) > 1
""").fetchdf()

print(f"CustomerID encore en doublon : {len(doublons_client)}")

CustomerID distincts dans retail_clean : 5943
Lignes dans DIM_CUSTOMER : 5943
CustomerID encore en doublon : 0

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_GEOGRAPHY AS
    WITH geo_frequente AS (
        SELECT
            Country,
            Continent,
            Region,
            Currency,
            ROW_NUMBER() OVER (
                PARTITION BY Country
                ORDER BY COUNT(*) DESC, Continent ASC
            ) AS rn
        FROM retail_clean
        WHERE Country IS NOT NULL
        GROUP BY Country, Continent, Region, Currency
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY Country) AS GeographyID,
        Country,
        Continent,
        Region,
        Currency
    FROM geo_frequente
    WHERE rn = 1
""")

con.sql("SELECT * FROM DIM_GEOGRAPHY LIMIT 15").fetchdf()

,GeographyID,Country,Continent,Region,Currency
0,1,australia,Oceania,Australia and New Zealand,AUD
1,2,belgium,Europe,Western Europe,EUR
2,3,brazil,South America,South America,BRL
3,4,canada,North America,North America,CAD
4,5,denmark,Europe,Northern Europe,DKK
5,6,france,Europe,Western Europe,EUR
6,7,germany,Europe,Western Europe,EUR
7,8,ireland,Europe,Western Europe,EUR
8,9,italy,Europe,Southern Europe,EUR
9,10,japan,Asia,Eastern Asia,JPY
10,11,netherlands,Europe,Western Europe,EUR
11,12,norway,Europe,Northern Europe,NOK
12,13,poland,Europe,Eastern Europe,PLN
13,14,portugal,Europe,Southern Europe,EUR
14,15,singapore,Asia,South-Eastern Asia,SGD

In [ ]:
nb_country_distinct = con.sql("SELECT COUNT(DISTINCT Country) AS nb FROM retail_clean WHERE Country IS NOT NULL").fetchdf()
nb_dim = con.sql("SELECT COUNT(*) AS nb FROM DIM_GEOGRAPHY").fetchdf()

print(f"Country distincts dans retail_clean : {nb_country_distinct['nb'][0]}")
print(f"Lignes dans DIM_GEOGRAPHY : {nb_dim['nb'][0]}")

doublons_geo = con.sql("""
    SELECT Country, COUNT(*) AS nb_lignes
    FROM DIM_GEOGRAPHY
    GROUP BY Country
    HAVING COUNT(*) > 1
""").fetchdf()

print(f"Country encore en doublon : {len(doublons_geo)}")

Country distincts dans retail_clean : 22
Lignes dans DIM_GEOGRAPHY : 22
Country encore en doublon : 0

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_WAREHOUSE AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY WarehouseID) AS WarehouseKey,
        WarehouseID
    FROM (
        SELECT DISTINCT WarehouseID
        FROM retail_clean
        WHERE WarehouseID IS NOT NULL
    )
""")

con.sql("SELECT * FROM DIM_WAREHOUSE LIMIT 15").fetchdf()

   WarehouseKey WarehouseID
0             1    WH-AF-01
1             2    WH-AS-01
2             3    WH-EU-01
3             4    WH-EU-02
4             5    WH-NA-01
5             6    WH-OC-01
6             7    WH-SA-01
7             8    WH-UK-01
8             9    WH-UK-02

In [ ]:
nb_warehouse_distinct = con.sql("SELECT COUNT(DISTINCT WarehouseID) AS nb FROM retail_clean WHERE WarehouseID IS NOT NULL").fetchdf()
nb_dim = con.sql("SELECT COUNT(*) AS nb FROM DIM_WAREHOUSE").fetchdf()

print(f"WarehouseID distincts dans retail_clean : {nb_warehouse_distinct['nb'][0]}")
print(f"Lignes dans DIM_WAREHOUSE : {nb_dim['nb'][0]}")

WarehouseID distincts dans retail_clean : 9
Lignes dans DIM_WAREHOUSE : 9

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_ORDER_CONTEXT AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY SalesChannel, PaymentMethod, PromotionCode, DiscountRate, OrderStatus) AS OrderContextID,
        SalesChannel,
        PaymentMethod,
        PromotionCode,
        DiscountRate,
        OrderStatus
    FROM (
        SELECT DISTINCT
            SalesChannel,
            PaymentMethod,
            PromotionCode,
            DiscountRate,
            OrderStatus
        FROM retail_clean
    )
""")

con.sql("SELECT * FROM DIM_ORDER_CONTEXT LIMIT 15").fetchdf()

,OrderContextID,SalesChannel,PaymentMethod,PromotionCode,DiscountRate,OrderStatus
0,1,Marketplace,PayPal,CLEARANCE,0.0,Cancelled
1,2,Marketplace,PayPal,CLEARANCE,0.0,Completed
2,3,Marketplace,PayPal,CLEARANCE,0.2,Cancelled
3,4,Marketplace,PayPal,CLEARANCE,0.2,Completed
4,5,Marketplace,PayPal,CLEARANCE,0.2,Returned
5,6,Marketplace,PayPal,CLEARANCE,0.2,None
6,7,Marketplace,PayPal,CLEARANCE,0.3,Cancelled
7,8,Marketplace,PayPal,CLEARANCE,0.3,Completed
8,9,Marketplace,PayPal,CLEARANCE,None,Cancelled
9,10,Marketplace,PayPal,CLEARANCE,None,Completed
10,11,Marketplace,PayPal,CLEARANCE,None,None
11,12,Marketplace,PayPal,NONE,0.0,Cancelled
12,13,Marketplace,PayPal,NONE,0.0,Completed
13,14,Marketplace,PayPal,NONE,0.0,Returned
14,15,Marketplace,PayPal,NONE,0.0,None

In [ ]:
nb_dim = con.sql("SELECT COUNT(*) AS nb FROM DIM_ORDER_CONTEXT").fetchdf()
print(f"Nombre de combinaisons distinctes dans DIM_ORDER_CONTEXT : {nb_dim['nb'][0]}")

Nombre de combinaisons distinctes dans DIM_ORDER_CONTEXT : 274

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE FACT_SALES AS
    SELECT
        r.OrderLineID,
        r.Invoice,
        d.DateID,
        p.ProductID,
        c.CustomerKey,
        g.GeographyID,
        w.WarehouseKey,
        oc.OrderContextID,
        r.Quantity,
        r.UnitPriceGBP,
        r.UnitCostGBP,
        r.DeliveryTime,
        r.Quantity * TRY_CAST(r.UnitPriceGBP AS DOUBLE) AS SalesAmount
    FROM retail_clean r
    LEFT JOIN DIM_DATE d
        ON r.InvoiceDate = d.Date
    LEFT JOIN DIM_PRODUCT p
        ON r.StockCode = p.StockCode
    LEFT JOIN DIM_CUSTOMER c
        ON r.CustomerID = c.CustomerID
    LEFT JOIN DIM_GEOGRAPHY g
        ON r.Country = g.Country
    LEFT JOIN DIM_WAREHOUSE w
        ON r.WarehouseID = w.WarehouseID
    LEFT JOIN DIM_ORDER_CONTEXT oc
        ON r.SalesChannel IS NOT DISTINCT FROM oc.SalesChannel
        AND r.PaymentMethod IS NOT DISTINCT FROM oc.PaymentMethod
        AND r.PromotionCode IS NOT DISTINCT FROM oc.PromotionCode
        AND r.DiscountRate IS NOT DISTINCT FROM oc.DiscountRate
        AND r.OrderStatus IS NOT DISTINCT FROM oc.OrderStatus
""")

con.sql("SELECT * FROM FACT_SALES LIMIT 10").fetchdf()

,OrderLineID,Invoice,DateID,ProductID,CustomerKey,GeographyID,WarehouseKey,OrderContextID,Quantity,UnitPriceGBP,UnitCostGBP,DeliveryTime,SalesAmount
0,352157,523645,241,30,493,21,9,4,1.0,16.78,8.79,4,16.78
1,693116,550999,413,30,5325,21,8,83,4.0,16.78,8.79,2,67.12
2,800165,560926,485,30,5943,21,9,31,1.0,16.78,8.79,8,16.78
3,734274,555149,440,30,5943,21,8,170,1.0,16.78,8.79,1,16.78
4,820257,562717,499,30,5943,21,9,129,1.0,16.78,8.79,12,16.78
5,887148,568368,540,30,5652,21,8,92,1.0,16.78,8.79,8,16.78
6,287019,517331,193,30,5322,21,8,72,20.0,16.78,8.79,3,335.60
7,750513,556636,451,30,5943,21,9,4,1.0,16.78,8.79,1,16.78
8,847993,565233,520,30,5943,21,8,57,2.0,16.78,8.79,13,33.56
9,694778,551173,413,30,5943,21,8,63,1.0,16.78,8.79,7,16.78

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE DIM_CUSTOMER AS
    SELECT
        CustomerID,
        CustomerSegment,
        CustomerType,
        LoyaltyProgram
    FROM DIM_CUSTOMER
""")

con.execute("""
    CREATE OR REPLACE TABLE DIM_WAREHOUSE AS
    SELECT
        WarehouseID
    FROM DIM_WAREHOUSE
""")

con.sql("SELECT * FROM DIM_CUSTOMER LIMIT 5").fetchdf()

  CustomerID CustomerSegment    CustomerType LoyaltyProgram
0    12346.0             VIP  Small business           Gold
1    12347.0           Loyal  Small business         Silver
2    12348.0             VIP        Retailer           Gold
3    12349.0         Regular        Retailer         Bronze
4    12350.0         Regular      Individual         Bronze

In [ ]:
con.execute("""
    CREATE OR REPLACE TABLE FACT_SALES AS
    SELECT
        r.OrderLineID,
        r.Invoice,
        d.DateID,
        p.ProductID,
        c.CustomerID,
        g.GeographyID,
        w.WarehouseID,
        oc.OrderContextID,
        r.Quantity,
        r.UnitPriceGBP,
        r.UnitCostGBP,
        r.DeliveryTime,
        r.Quantity * TRY_CAST(r.UnitPriceGBP AS DOUBLE) AS SalesAmount
    FROM retail_clean r
    LEFT JOIN DIM_DATE d
        ON r.InvoiceDate = d.Date
    LEFT JOIN DIM_PRODUCT p
        ON r.StockCode = p.StockCode
    LEFT JOIN DIM_CUSTOMER c
        ON r.CustomerID = c.CustomerID
    LEFT JOIN DIM_GEOGRAPHY g
        ON r.Country = g.Country
    LEFT JOIN DIM_WAREHOUSE w
        ON r.WarehouseID = w.WarehouseID
    LEFT JOIN DIM_ORDER_CONTEXT oc
        ON r.SalesChannel IS NOT DISTINCT FROM oc.SalesChannel
        AND r.PaymentMethod IS NOT DISTINCT FROM oc.PaymentMethod
        AND r.PromotionCode IS NOT DISTINCT FROM oc.PromotionCode
        AND r.DiscountRate IS NOT DISTINCT FROM oc.DiscountRate
        AND r.OrderStatus IS NOT DISTINCT FROM oc.OrderStatus
""")

con.sql("SELECT * FROM FACT_SALES LIMIT 10").fetchdf()

,OrderLineID,Invoice,DateID,ProductID,CustomerID,GeographyID,WarehouseID,OrderContextID,Quantity,UnitPriceGBP,UnitCostGBP,DeliveryTime,SalesAmount
0,352157,523645,241,30,12838.0,21,WH-UK-02,4,1.0,16.78,8.79,4,16.78
1,693116,550999,413,30,17670.0,21,WH-UK-01,83,4.0,16.78,8.79,2,67.12
2,800165,560926,485,30,GUEST,21,WH-UK-02,31,1.0,16.78,8.79,8,16.78
3,734274,555149,440,30,GUEST,21,WH-UK-01,170,1.0,16.78,8.79,1,16.78
4,820257,562717,499,30,GUEST,21,WH-UK-02,129,1.0,16.78,8.79,12,16.78
5,887148,568368,540,30,17997.0,21,WH-UK-01,92,1.0,16.78,8.79,8,16.78
6,287019,517331,193,30,17667.0,21,WH-UK-01,72,20.0,16.78,8.79,3,335.60
7,750513,556636,451,30,GUEST,21,WH-UK-02,4,1.0,16.78,8.79,1,16.78
8,847993,565233,520,30,GUEST,21,WH-UK-01,57,2.0,16.78,8.79,13,33.56
9,694778,551173,413,30,GUEST,21,WH-UK-01,63,1.0,16.78,8.79,7,16.78

In [ ]:
nb_retail = con.sql("SELECT COUNT(*) AS nb FROM retail_clean").fetchdf()
nb_fact = con.sql("SELECT COUNT(*) AS nb FROM FACT_SALES").fetchdf()

print(f"Lignes dans retail_clean : {nb_retail['nb'][0]}")
print(f"Lignes dans FACT_SALES   : {nb_fact['nb'][0]}")

Lignes dans retail_clean : 1072336
Lignes dans FACT_SALES   : 1072336

In [ ]:
orphelins = con.sql("""
    SELECT
        COUNT(*) FILTER (WHERE DateID IS NULL) AS date_orphelines,
        COUNT(*) FILTER (WHERE ProductID IS NULL) AS produit_orphelines,
        COUNT(*) FILTER (WHERE CustomerID IS NULL) AS client_orphelines,
        COUNT(*) FILTER (WHERE GeographyID IS NULL) AS geo_orphelines,
        COUNT(*) FILTER (WHERE WarehouseID IS NULL) AS warehouse_orphelines,
        COUNT(*) FILTER (WHERE OrderContextID IS NULL) AS context_orphelines
    FROM FACT_SALES
""").fetchdf()

orphelins

,date_orphelines,produit_orphelines,client_orphelines,geo_orphelines,warehouse_orphelines,context_orphelines
0,10543,0,0,0,0,0

In [ ]:
# Est-ce que ces 10543 lignes ont vraiment un InvoiceDate NULL dans retail_clean ?
diagnostic_date = con.sql("""
    SELECT
        COUNT(*) AS total_lignes,
        COUNT(*) FILTER (WHERE InvoiceDate IS NULL) AS invoicedate_null
    FROM retail_clean
""").fetchdf()

diagnostic_date

   total_lignes  invoicedate_null
0       1072336             10543

In [ ]:
import os
os.makedirs("parquet_export", exist_ok=True)

In [ ]:
tables = ["DIM_DATE", "DIM_PRODUCT", "DIM_CUSTOMER", "DIM_GEOGRAPHY",
          "DIM_WAREHOUSE", "DIM_ORDER_CONTEXT", "FACT_SALES"]

for table in tables:
    con.execute(f"""
        COPY {table} TO 'parquet_export/{table}.parquet' (FORMAT PARQUET)
    """)
    print(f"✅ {table} exporté")

✅ DIM_DATE exporté
✅ DIM_PRODUCT exporté
✅ DIM_CUSTOMER exporté
✅ DIM_GEOGRAPHY exporté
✅ DIM_WAREHOUSE exporté
✅ DIM_ORDER_CONTEXT exporté
✅ FACT_SALES exporté

In [ ]:
con.execute("""
    COPY retail_clean TO 'retail_clean.csv' (FORMAT CSV, HEADER TRUE)
""")
print("✅ retail_clean.csv exporté")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ retail_clean.csv exporté